### ISSUE TITLE
Bug: Asset supply initial/circulation

### ISSUE THREAD

**Issue by crussell-figure** [provenance-io/explorer-frontend#63]
## Summary of Bug

Asset List and Asset single pages are not using the `response.supply.initial` value. 

Asset List:
Currently using `supply.circulation` for the Circulation column, but the Supply column is empty. Should be using `supply.initial`. Also rename to Initial Supply.

```
holdingAccount: "tp1pr93cqdh4kfnmrknhwa87a5qrwxw9k3dhkszp0"
marker: "nhash"
status: "ACTIVE"
supply: 
  circulation: "100000000000000000000"
  initial: "100000000000000000000"
```

Asset single:
For Supply field, currently showing `supply.circulation` / nothing. Should probably split them up for Circulation and Initial Supply with `supply.circulation` and `supply.initial` respectively. 

```
attributes: []
holderCount: 221
holdingAccount: "tp1pr93cqdh4kfnmrknhwa87a5qrwxw9k3dhkszp0"
managingAccounts: 
  allowGovControl: true
  managers: {tp1kmaut7y3psh46lw53hgm4967zfxpq5ls2m2w7v: ["WITHDRAW"]}
marker: "nhash"
markerStatus: "ACTIVE"
metadata: {}
mintable: false
supply: 
  circulation: "100000000000000000000"
  initial: "100000000000000000000"
tokens: 
  fungibleCount: 1
  nonFungibleCount: 0
txnCount: 920330
```

Also should be using SI abbreviations for super large numbers. Example: https://nyancat.iobscan.io/#/assets/ntvassets

## Version

latest

## Steps to Reproduce

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
